# Generated by Django 4.1.6 on 2023-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_generacion', models.IntegerField(choices=[(1, 'Primera Generación'), (2, 'Segunda Generación'), (3, 'Tercera Generación'), (4, 'Cuarta Generación'), (5, 'Quinta Generación'), (6, 'Sexta Generación'), (7, 'Séptima Generación')])),
            ],
        ),
    ]
